---
- name: Helm add repo
  shell: helm repo add {{ url_helm_repo }}
  register: prometheus_add_repo

- name: Helm update
  shell: helm repo update
  register: prometheus_repo_update

- name: Instalando o Prometheus Operator
  shell: helm install {{ deploy_prometheus }}
  register: prometheus_install

...
